Refactor tx
LemoFoundationLtd/lemochain-core pull request #64
Opened 2019-05-23 06:27 UTC by zyjblockchain

1. 重构执行交易部分
2. 编写重构之后的交易的测试用例
3. 预估交易gas和readContract调用方法的重构

2019-05-23 10:40 UTC, lnkyan requested changes

2019-05-23 10:40 UTC, lnkyan commented on chain/transaction/asset_tx.go
> +	newAsset := asset.Clone()
为什么要clone

2019-05-23 10:40 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +func NewTxProcessor(reward common.Address, chainID uint16, blockLoader BlockLoader, am *account.Manager, db protocol.ChainDB) *TxProcessor {
reward命名不合适，不看函数实现不知道是干嘛的

2019-05-23 10:40 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +func (p *TxProcessor) votesChange(initialSenderBalance, initialRecipientBalance *big.Int, tx *types.Transaction, gasUsed uint64) error {
如果在智能合约中对某账户进行了转账，这里检测不出来。所以票数的变化应该放到manager的Finalise里去，根据BalanceLog来做更新

2019-05-23 10:40 UTC, lnkyan commented on network/cache.go
> +	// for i := 0; i < length; i++ {
是否可以删了？

2019-05-23 10:40 UTC, lnkyan commented on chain/transaction/asset_tx.go
> +		r.am.RevertToSnapshot(snapshot)
尽量统一处理所有异常情况，要么都回滚，要么都不回滚

2019-05-25 02:46 UTC, lemochainxgq commented on chain/transaction/asset_tx.go
> +	freeze, err := issuerAcc.GetAssetCodeState(assetCode, types.AssetFreeze)
如果err不为nil呢？

2019-05-25 10:29 UTC, lemochainxgq approved these changes

2019-05-25 10:43 UTC, closed without merging