Multi sign tx
LemoFoundationLtd/lemochain-core pull request #67
Opened 2019-05-28 06:27 UTC by zyjblockchain

#62

2019-05-28 09:59 UTC, lemochainxgq commented on chain/transaction/set_multisig_account_tx.go
> +	for _, v := range newSigners {
算法错误

2019-05-28 09:59 UTC, lemochainxgq commented on chain/transaction/set_multisig_account_tx.go
> +	var totalWeight uint8 = 0
total weight溢出

2019-05-28 10:00 UTC, lemochainxgq commented on chain/transaction/set_multisig_account_tx.go
> +	if totalWeight <= SignersWeight {
total weight < signersweight

2019-05-28 10:15 UTC, lemochainxgq commented on chain/transaction/set_multisig_account_tx.go
> +		if tempMap[oldSigners[i].Address] != 0 {
最好用：_, ok := tempMap[oldSigners[i].Address]，可读性好点

2019-05-28 10:28 UTC, lemochainxgq commented on chain/transaction/tx_processor.go
> +		var totalWeight uint8 = 0
totalweight溢出

2019-05-28 10:28 UTC, lemochainxgq commented on chain/transaction/tx_processor.go
> +		if totalWeight < SignersWeight {
可以=

2019-05-28 10:44 UTC, lemochainxgq commented on chain/transaction/set_multisig_account_tx.go
> +		if m[v.Address] != 0 {
_, ok := m[v.Address]

2019-05-28 10:47 UTC, lemochainxgq commented on chain/transaction/set_multisig_account_tx.go
> +	err := json.Unmarshal(data, &newSigners)
最多多少个signer

2019-05-28 10:54 UTC, lemochainxgq approved these changes

2019-05-29 01:44 UTC, lnkyan requested changes

2019-05-29 01:44 UTC, lnkyan commented on chain/transaction/tx_processor.go
>  	SignersWeight        = 100
命名不合适

2019-05-29 01:44 UTC, lnkyan commented on chain/transaction/set_multisig_account_tx.go
>  	}
逻辑太复杂，直接替换就行了

2019-05-29 01:50 UTC, lnkyan commented on chain/transaction/set_multisig_account_tx.go
> +	} else { // 临时账户
这个版本没有临时账户，而且也不应该这样判断。把这部分逻辑删了吧

2019-05-29 01:58 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +	switch {
改成if else吧，如果觉得大括号里面的内容太长，就应该拆函数。而不是搞什么switch，并且还产生了一个奇怪的default

2019-05-29 02:02 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +			totalWeight = totalWeight + int64(signersMap[Addr])
需要判空吧

2019-05-29 02:03 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +		totalSigners := fromAcc.GetSigners()
为什么不直接用accSigners

2019-05-29 02:08 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +func (p *TxProcessor) checkSignersBySender(sender common.Address, signers []common.Address) error {
命名不合适，改成checkSignersWeight吧

2019-05-29 08:43 UTC, lnkyan approved these changes

2019-05-29 09:22 UTC, merged