fix(tx): Fix candidate tx
LemoFoundationLtd/lemochain-core pull request #94
Opened 2019-07-23 06:18 UTC by zyjblockchain

### 修改内容：
1. 注册候选节点通过传入交易amount来质押押金，押金要大于等于500万LEMO才能注册
2. 注册成功之后可以通过修改候选节点信息的方式追加质押押金。
3. 质押押金兑换成票数为75LEMO/票，投票用户的balance兑换成票数为100LEMO/票，票数只能取整。
4. 注销候选节点退回质押押金统一在本届发放奖励区块中进行退换。

2019-07-24 08:50 UTC, lnkyan requested changes

2019-07-24 08:50 UTC, lnkyan commented on chain/consensus/assembler.go
> +						candidateAcc.SetBalance(new(big.Int).Add(candidateAcc.GetBalance(), pledgeAmount))
没有更新票数

2019-07-24 08:50 UTC, lnkyan commented on chain/consensus/chain_for_test.go
>  			// 注册费用1000lemo
这些注释修改一下吧，要么就别写具体数字

2019-07-24 08:50 UTC, lnkyan commented on chain/consensus/assembler.go
> +				oldNum := new(big.Int).Div(oldBalance, params.VoteExchangeRate)
统一通过changelog来更新票数

2019-07-24 08:50 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +				// 新老质押的金额与75Lemo求模，把求的数比较如果增加了则增加相应的票数
注释不对，没找到哪有求模

2019-07-24 08:50 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
>  		// Checking the balance is not enough
```suggestion
		// Check if the balance is not enough
```

2019-07-24 08:50 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +	if ok && candidateState == params.IsCandidateNode {
函数过大需要拆分

2019-07-24 08:50 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +		if (oldNodeAddress != common.Address{}) { // 因为注册候选节点之后当前账户默认投票给自己，所以要进行修改投票人的操作
不必投给自己了，给自己的票已经通过押金获得了

2019-07-24 08:50 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +		c.Transfer(c.am, candidateAddress, params.CandidateDepositAddress, tx.Amount())
先转账，再增加票数吧。现在先增加票数，万一增加完出了个bug跳出去了，余额又没减，就会成为一个很严重的漏洞

2019-07-24 08:50 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +		// Set up voter account
这里面的逻辑都写了两遍。应该把设置voteFor和修改票数分成两个环节，拆到两个函数里

2019-07-24 08:50 UTC, lnkyan commented on store/chain_database.go
> +func (database *ChainDatabase) GetAllCandidates() ([]common.Address, error) {
能否在这把已注销的去掉，到时候需要一个api获取所有候选节点

2019-07-24 12:26 UTC, zyjblockchain commented on store/chain_database.go
> +func (database *ChainDatabase) GetAllCandidates() ([]common.Address, error) {
这时db里面的操作，不能获取到对应address的候选节点信息，所以判断不了是否取消了candidate

2019-07-25 14:47 UTC, lnkyan requested changes

2019-07-25 14:47 UTC, lnkyan commented on chain/consensus/assembler.go
> +	transaction.SetCandidateVotesByChangeBalance(am)
名字太长，改成ChangeVotesByBalance吧

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +func (c *CandidateVoteEnv) firstRegisterCandidate(pledgeAmount *big.Int, register common.Address, txBuildProfile types.Profile) error {
命名不必first，一共只能有一次

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +	if !ok || candidateState == "" { // 表示第一次注册候选节点，等于""为如果一个账户第一次注册候选交易失败之后，回滚会让map中的值回滚为零值，string类型的0值为"".箱子交易中容易出现此情况。
回滚了map怎么还能存在？ok应该为false才对。否则就是回滚不干净，应该算bug

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +			return ErrAgainRegister
改名为ErrRegisterAgain或者ErrRegisterTwice吧

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +func (c *CandidateVoteEnv) modifyCandidateInfo(amount *big.Int, senderAddr common.Address, txBuildProfile types.Profile) error {
注册候选人都拆成函数了。注销和修改为什么不拆开？

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +		return ErrOfAgainVote
命名为ErrAlreadyVoted或ErrVoteTwice

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +		initialSenderBalance = sender.GetBalance() // initialSenderBalance参数代表的是sender执行交易之前的balance值，为投票交易中计算初始票数使用
注释太长，不应该放在行尾

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +// handleTx 执行交易,返回消耗之后剩余的gas、evm中执行的error和交易执行不成功的error，注：initialSenderBalance参数代表的是sender执行交易之前的balance值，为投票交易中计算初始票数使用
改成多行注释排版，不然读起来太累，重点不突出。想要提醒的部分也没人注意的到

2019-07-25 14:47 UTC, lnkyan commented on chain/transaction/tx_processor.go
> +func SetCandidateVotesByChangeBalance(am *account.Manager) {
内部实现拆分成filterLogs(logs, BalanceLog)，getVotesChangesByLogs(logs)，和applyVotesChange(votesChanges)，会更淡出，更好测一些

2019-07-25 14:53 UTC, lnkyan commented on chain/consensus/assembler.go
> +			allCandidateAddressList, err := ba.db.GetAllCandidates()
下面这部分功能独立，也应该放进单独的函数。
并且这部分逻辑不应该放在termRewards大于0的这个if中吧。如果没有矿池奖励，就不能退押金了？

2019-07-26 03:32 UTC, zyjblockchain commented on chain/consensus/assembler.go
> +			allCandidateAddressList, err := ba.db.GetAllCandidates()
括号太多看错了，写到里面去了

2019-07-26 06:16 UTC, lnkyan commented on chain/transaction/candidate_vote_tx.go
> +	if !ok || candidateState == "" { // 表示第一次注册候选节点，等于""为如果一个账户第一次注册候选交易失败之后，回滚会让map中的值回滚为零值，string类型的0值为"".箱子交易中容易出现此情况。
重新弄个pr来解决，顺便检查箱子交易中其它各种交易被回滚后，能否回滚干净

2019-07-26 06:56 UTC, lnkyan approved these changes

2019-07-26 06:57 UTC, merged